# Generated by Django 5.0.6 on 2024-06-27 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='due_to',
            new_name='due_at',
        ),
    ]
